import type { NextPage } from 'next'
import Head from 'next/head';
import Search from './search';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <Search />
      </main>
    </>
  )
}

export default Home
